apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkgs-cluster-1
  namespace: primp-industries
spec:
  distribution:
    version: v1.18.10
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
        - 10.1.1.0/22
      services:
        cidrBlocks:
        - 10.1.4.0/22
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: tanzu-gold-storage-policy
    workers:
      count: 3
      class: best-effort-small
      storageClass: tanzu-gold-storage-policy
